### ISSUE TITLE
复现代码遇到尺寸bug

### ISSUE THREAD

**Issue by 2ephyrus** [fangwei123456/Parallel-Spiking-Neuron#6]
报错信息如下：
Traceback (most recent call last):
  File "/root/wanjie-data/project2/cifar10dvs/train_vgg.py", line 218, in <module>
    loss, acc = train(parallel_model, device, train_loader, criterion, optimizer, epoch, args)
  File "/root/wanjie-data/project2/cifar10dvs/train_vgg.py", line 96, in train
    outputs = model(images)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/wanjie-data/project2/cifar10dvs/models.py", line 294, in forward
    x = self.classifier(x)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/wanjie-data/project2/cifar10dvs/models.py", line 23, in forward
    y_seq = self.module(x_seq.flatten(0, 1).contiguous())
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x32768 and 4608x10)

**Comment by Takoyaki-h** [comment]
您好，我也遇到了这个问题，不知道现在得到解决了吗

**Comment by fangwei123456** [comment]
不确定是不是之前sj主框架中的bug所致（后来更新过一次）。可以从GitHub安装最新sj框架（不是从pypi）再运行看看

**Comment by Takoyaki-h** [comment]
发现是全连接输入通道数不匹配的问题，已经解决了，谢谢。

**Comment by 2ephyrus** [comment]
问题已解决，不匹配的原因是transform未成功执行，导致输入尺寸没有成功降维至48。
具体原因是 setup的sj文件夹内，import路径有问题（引用了spikingjelly包，而不是spikingjelly文件夹）。
作两点调整：
1.train_vgg.py第十一行替换为：
`from sj.spikingjelly.datasets.cifar10_dvs import CIFAR10DVS`
2.sj.spikingjelly.datasets文件夹内的cifar10_dvs.py第三行替换为：
`from .. import datasets as sjds`
